sudo: required
services:
  - docker

before_install:
  - docker build -t mboulon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mboulon/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react-simple"
  env: "Dockerreactsimple-env"
  bucket_name: "elasticbeanstalk-eu-west-1-972700432989"
  bucket_path: "docker-react-simple"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY